# Generated by Django 5.2.3 on 2025-07-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerdigital_app', '0002_profile_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
    ]
