# Generated by Django 5.2.3 on 2025-07-24 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdigital_app', '0003_remove_profile_credit_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeorder',
            name='manual_profit',
        ),
        migrations.RemoveField(
            model_name='tradeorder',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='tradeorder',
            name='yield_percent',
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='potential_profit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='balance',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='direction',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='expiry_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='pair',
            field=models.CharField(max_length=20),
        ),
    ]
