# Generated by Django 5.2.3 on 2025-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdigital_app', '0004_remove_tradeorder_manual_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorder',
            name='yield_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
