# Generated by Django 5.2.3 on 2025-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdigital_app', '0005_tradeorder_yield_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorder',
            name='manual_profit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
