# Generated by Django 5.2.3 on 2025-07-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdigital_app', '0006_tradeorder_manual_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorder',
            name='is_win',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
