# Generated by Django 5.2.3 on 2025-07-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdigital_app', '0009_tradeorder_entry_price_tradeorder_exit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeorder',
            name='exit_price',
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='outcome_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='entry_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
