# Generated by Django 5.2.3 on 2025-07-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdigital_app', '0010_remove_tradeorder_exit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeorder',
            name='outcome_price',
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
