# Generated by Django 5.2.3 on 2025-07-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerdigital_app', '0013_tradeorder_user_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeorder',
            name='user_deleted',
        ),
    ]
